version: "3.9"

services:
  nginx:
    image: nginx:latest 
    volumes:
       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
       - .:/var/www/html
    ports:
      - ${HTTP_PORT_HOST}:80
    depends_on:
      - php-fpm
    networks:
      - backend_net

  php-fpm:
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        XDEBUG_ENABLE: ${XDEBUG_ENABLE:-false}
        XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
        XDEBUG_MODE: ${XDEBUG_MODE}
        XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
    volumes:
      - .:/var/www/html
#      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - backend_net
    extra_hosts:
      - host.docker.internal:host-gateway
# use host mysql      
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
#      - ${STORE_LIB_MYSQL}:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
    ports:
      - ${MYSQL_EXT_PORT}:3306
    networks:
      - backend_net

networks:
  backend_net:
    ipam:
      driver: default